version: '3.8'

services:
  bravebot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped