# وضع التشغيل: mock للتجربة / live لتفعيل الـ APIs الحقيقية
mode: "mock"

# بيانات API الخاصة بـ Amazon
amazon_api:
  access_key: "YOUR_AMAZON_ACCESS_KEY"
  secret_key: "YOUR_AMAZON_SECRET_KEY"
  partner_tag: "YOUR_PARTNER_TAG"

# بيانات API الخاصة بـ eBay
ebay_api:
  app_id: "YOUR_EBAY_APP_ID"
  cert_id: "YOUR_EBAY_CERT_ID"
  dev_id: "YOUR_EBAY_DEV_ID"

# أقصى وأدنى سعر مسموح لفحص المنتجات (مفتوح لحد مليون في النسخة الشخصية)
max_price: 1000000
min_price: 0.01

# ID الخاص بالمالك (أنت)
owner_id: 1645253698   # استبدل الرقم بـ ID بتاعك لو اتغير

# IDs إضافية للمشرفين (اختياري – سيبها فاضية)
admin_ids: []

# تعطيل الحدود (Rate Limit) لأن البوت شخصي
rate_limit:
  checks_per_hour: 999999
  checks_per_day: 999999
